# Site settings
title: Igreja Presbiteriana Pedras Vivas
email: contato@ippedrasvivas.org.br
description: > # this means to ignore newlines until "baseurl:"
 Nossa descrição
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ippedrasvivas" # the base hostname & protocol for your site

twitter_username:
github_username:

address:
  - line: Igreja Presbiteriana Pedras Vivas
  - line: Av. Dr. Euríco Chaves, 39 - Casa Amarela
  - line: "Recife, Pernambuco, Brasil"
  # Feel free to add more lines here

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
